### ISSUE TITLE
Is it time to go python3?

### ISSUE THREAD

**Issue by wsakernel** [gryf/uc1541#2]
The plugin does not work with a regular Debian installation unless you have installed the package python-is-python3. From its description: 

"Starting with the Debian 11 (bullseye) and Ubuntu 20.04 LTS (focal)
releases, all python packages use explicit python3 or python2
interpreter and do not use unversioned /usr/bin/python at all. Some
third-party code is now predominantly python3 based, yet may use
/usr/bin/python.

This is a convenience package which ships a symlink to point
the /usr/bin/python interpreter at the current default python3. It may
improve compatibility with other modern systems, whilst breaking some
obsolete or 3rd-party software.

No packages may declare dependencies on this package."

python2 is deprecated now by many distributions. Maybe it is a good idea to switch to python3, so it will work out of the box for modern distros?

**Comment by gryf** [comment]
It is python3 compatible. Also you should have it working with latest midnight commander package. Said that, if there is an issue with your distribution you should fill the bug report for midnight commander and this script in Debian bugzilla. In my distro I have python executable which can be selected from available python3 interpreters.

**Comment by gryf** [comment]
Ok, I've dropped Python2.x support with version 3.5. It should be good now, enjoy.

**Comment by wsakernel** [comment]
Cool, thanks!
